#**Data** **preprocessing**

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('/content/596958_1073629_bundle_archive (1).zip')

In [3]:
dataset

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0        1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1        2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2        3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3        4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4        5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0
..     ...    ...    ...      ...  ...             ...    ...         ...       ...
210    211      M  80.60   Others  ...         Mkt&Fin  74.49      Placed  400000.0
211    212      M  58.00   Others  ...         Mkt&Fin  53.62      Placed  275000.0
212    213      M  67.00   Others  ...         Mkt&Fin  69.72      Placed  295000.0
213    214      F  74.00   Others  ...          Mkt&HR  60.23      Placed  204000.0
214    215      M  62.00  Central  ...          Mkt&HR  60.22  Not Placed       NaN

[215 rows x 15 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object 
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


In [5]:
dataset['status'].unique()

array(['Placed', 'Not Placed'], dtype=object)

#**Seperate** **Features** **and** **Target**


In [6]:
X = dataset.drop(['status','salary'],axis=1)
y = dataset.iloc[:,-2]

In [8]:
X

sl_no gender  ssc_p    ssc_b  ...  workex etest_p specialisation  mba_p
0        1      M  67.00   Others  ...      No    55.0         Mkt&HR  58.80
1        2      M  79.33  Central  ...     Yes    86.5        Mkt&Fin  66.28
2        3      M  65.00  Central  ...      No    75.0        Mkt&Fin  57.80
3        4      M  56.00  Central  ...      No    66.0         Mkt&HR  59.43
4        5      M  85.80  Central  ...      No    96.8        Mkt&Fin  55.50
..     ...    ...    ...      ...  ...     ...     ...            ...    ...
210    211      M  80.60   Others  ...      No    91.0        Mkt&Fin  74.49
211    212      M  58.00   Others  ...      No    74.0        Mkt&Fin  53.62
212    213      M  67.00   Others  ...     Yes    59.0        Mkt&Fin  69.72
213    214      F  74.00   Others  ...      No    70.0         Mkt&HR  60.23
214    215      M  62.00  Central  ...      No    89.0         Mkt&HR  60.22

[215 rows x 13 columns]

In [9]:
y

0          Placed
1          Placed
2          Placed
3      Not Placed
4          Placed
          ...    
210        Placed
211        Placed
212        Placed
213        Placed
214    Not Placed
Name: status, Length: 215, dtype: object

In [10]:
X = X.to_numpy()

In [11]:
y = y.to_numpy()

#**Encoding**

**##One hot encoder for feature**s

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1,3,5,6,8,9,11])], remainder='passthrough')

In [15]:
X = np.array(ct.fit_transform(X))

In [16]:
X

array([[0.0, 1.0, 0.0, ..., 58.0, 55.0, 58.8],
       [0.0, 1.0, 1.0, ..., 77.48, 86.5, 66.28],
       [0.0, 1.0, 1.0, ..., 64.0, 75.0, 57.8],
       ...,
       [0.0, 1.0, 0.0, ..., 73.0, 59.0, 69.72],
       [1.0, 0.0, 0.0, ..., 58.0, 70.0, 60.23],
       [0.0, 1.0, 1.0, ..., 53.0, 89.0, 60.22]], dtype=object)

In [17]:
temp= pd.DataFrame(data=X)

In [18]:
temp

0  1  2  3  4  5  6  7  8   ... 13 14 15   16     17     18     19    20     21
0    0  1  0  1  0  1  0  1  0  ...  0  0  1    1     67     91     58    55   58.8
1    0  1  1  0  0  1  0  0  1  ...  1  1  0    2  79.33  78.33  77.48  86.5  66.28
2    0  1  1  0  1  0  1  0  0  ...  0  1  0    3     65     68     64    75   57.8
3    0  1  1  0  1  0  0  0  1  ...  0  0  1    4     56     52     52    66  59.43
4    0  1  1  0  1  0  0  1  0  ...  0  1  0    5   85.8   73.6   73.3  96.8   55.5
..  .. .. .. .. .. .. .. .. ..  ... .. .. ..  ...    ...    ...    ...   ...    ...
210  0  1  0  1  0  1  0  1  0  ...  0  1  0  211   80.6     82   77.6    91  74.49
211  0  1  0  1  0  1  0  0  1  ...  0  1  0  212     58     60     72    74  53.62
212  0  1  0  1  0  1  0  1  0  ...  1  1  0  213     67     67     73    59  69.72
213  1  0  0  1  0  1  0  1  0  ...  0  0  1  214     74     66     58    70  60.23
214  0  1  1  0  0  1  0  0  1  ...  0  0  1  215     62     58     53    89  60.22

[215 rows x 22 columns]

**Splitting data into train and test set**

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#**Label** **encoder** **for** **target**

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()

In [23]:
y1_train  = le.fit_transform(y_train)

In [24]:
y1_test = le.fit_transform(y_test)

#**Standardization**

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc = StandardScaler()

In [27]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

#**Applying** **different** **algorithms**

###Logistic Regression
###KNN
###Decision Tree
###Random Forest
###Linear SVC





In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [29]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel = 'linear')
ks_cla = SVC(kernel = 'rbf')

In [30]:
l_cla.fit(X_train, y1_train)
k_cla.fit(X_train, y1_train)
d_cla.fit(X_train, y1_train)
r_cla.fit(X_train, y1_train)
s_cla.fit(X_train, y1_train)
ks_cla.fit(X_train, y1_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

##**Predicting**

In [31]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
l_c = confusion_matrix(y1_test, l_pred)
k_c = confusion_matrix(y1_test, k_pred)
d_c = confusion_matrix(y1_test, d_pred)
r_c = confusion_matrix(y1_test, r_pred)
s_c = confusion_matrix(y1_test, s_pred)
ks_c = confusion_matrix(y1_test, ks_pred)

In [34]:
l_c

array([[ 9,  6],
       [ 4, 24]])

In [35]:
k_c

array([[ 7,  8],
       [ 5, 23]])

In [36]:
d_c

array([[ 9,  6],
       [ 4, 24]])

In [37]:
r_c

array([[ 7,  8],
       [ 2, 26]])

In [38]:
s_c

array([[12,  3],
       [ 3, 25]])

In [39]:
ks_c

array([[ 9,  6],
       [ 3, 25]])

#**Result**

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
l_a = accuracy_score(y1_test, l_pred)
k_a = accuracy_score(y1_test, k_pred)
d_a = accuracy_score(y1_test, d_pred)
r_a = accuracy_score(y1_test, r_pred)
s_a = accuracy_score(y1_test, s_pred)
ks_a = accuracy_score(y1_test, ks_pred)

In [42]:
print('Logistic Regression: ' + str(l_a) + '\nKNeighbors: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.7674418604651163
KNeighbors: 0.6976744186046512
Decision Tree: 0.7674418604651163
Random Forest: 0.7674418604651163
Linear SVC: 0.8604651162790697
Kernel SVC: 0.7674418604651163


#**Conclusion**

##Linear SVC has more accuracy 